<?php
// backend/admin.php — Admin Dashboard with tabs
// Tabs: Documents en Attente | Gérer Années | Gérer Matières

session_start();
if (($_SESSION['user_role'] ?? '') !== 'admin') {
    header("Location: ../index.html");
    exit("Accès refusé.");
}
require_once __DIR__ . '/db.php';

$pdo = getDB();

// --- Fetch Notifications ---
$currentUserId = $_SESSION['user_id'] ?? 0;
$notifications = [];
if ($currentUserId) {
    // Fetch unread 'system' or 'error' notifications generated by background worker
    $notifStmt = $pdo->prepare("SELECT * FROM notifications WHERE user_id = ? AND is_read = 0 AND (type = 'system' OR type = 'error') ORDER BY created_at DESC");
    $notifStmt->execute([$currentUserId]);
    $notifications = $notifStmt->fetchAll(PDO::FETCH_ASSOC);

    // Mark them as read immediately so they don't show up twice
    if (!empty($notifications)) {
        $notifIds = array_column($notifications, 'id');
        $placeholders = implode(',', array_fill(0, count($notifIds), '?'));
        $pdo->prepare("UPDATE notifications SET is_read = 1 WHERE id IN ($placeholders)")->execute($notifIds);
    }
}

$tab = $_GET['tab'] ?? 'documents';
$success = $_GET['success'] ?? '';
$error = $_GET['error'] ?? '';

// --- Handle form submissions ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $formAction = $_POST['form_action'] ?? '';

    // Add Year
    if ($formAction === 'add_year') {
        $year = intval($_POST['year'] ?? 0);
        if ($year >= 2000 && $year <= 2099) {
            try {
                $stmt = $pdo->prepare("INSERT IGNORE INTO years (year) VALUES (?)");
                $stmt->execute([$year]);
                // Rebuild architecture via web process
                ob_start(); include __DIR__ . '/rebuild_structure.php'; ob_end_clean();
                shell_exec("cd " . escapeshellarg(__DIR__ . '/..') . " && python backend/build_docs.py");
                header("Location: admin.php?tab=years&success=Année $year ajoutée. L'architecture a été mise à jour.");
                exit;
            } catch (\PDOException $e) {
                header("Location: admin.php?tab=years&error=" . urlencode($e->getMessage()));
                exit;
            }
        }
    }

    // Add Subject
    if ($formAction === 'add_subject') {
        $subjectName = trim($_POST['subject_name'] ?? '');
        $semesterId = intval($_POST['semester_id'] ?? 0);
        if (!empty($subjectName) && $semesterId > 0) {
            try {
                $stmt = $pdo->prepare("INSERT IGNORE INTO subjects (name, semester_id, is_active) VALUES (?, ?, 1)");
                $stmt->execute([$subjectName, $semesterId]);
                // Rebuild architecture
                ob_start(); include __DIR__ . '/rebuild_structure.php'; ob_end_clean();
                shell_exec("cd " . escapeshellarg(__DIR__ . '/..') . " && python backend/build_docs.py");
                header("Location: admin.php?tab=subjects&success=Matière ajoutée et architecture regénérée.");
                exit;
            } catch (\PDOException $e) {
                header("Location: admin.php?tab=subjects&error=" . urlencode($e->getMessage()));
                exit;
            }
        }
    }

    // Toggle Subject Active
    if ($formAction === 'toggle_subject') {
        $subjectId = intval($_POST['subject_id'] ?? 0);
        if ($subjectId > 0) {
            $pdo->prepare("UPDATE subjects SET is_active = NOT is_active WHERE id = ?")->execute([$subjectId]);
            // Rebuild architecture
            ob_start(); include __DIR__ . '/rebuild_structure.php'; ob_end_clean();
            shell_exec("cd " . escapeshellarg(__DIR__ . '/..') . " && python backend/build_docs.py");
            header("Location: admin.php?tab=subjects&success=Statut modifié. Architecture mise à jour.");
            exit;
        }
    }
}

// --- Fetch data ---

// Pending Documents (with JOINs)
$pendingDocs = $pdo->query(
    "SELECT d.id, d.title, d.filename, d.created_at,
            s.name AS subject_name, dt.name AS type_name, y.year,
            l.name AS level_name, sem.name AS semester_name,
            u.name AS user_name
     FROM documents d 
     JOIN subjects s ON d.subject_id = s.id
     JOIN semesters sem ON s.semester_id = sem.id
     JOIN levels l ON sem.level_id = l.id
     JOIN document_types dt ON d.type_id = dt.id
     JOIN years y ON d.year_id = y.id
     LEFT JOIN users u ON d.user_id = u.id
     WHERE d.status = 'pending'
     ORDER BY d.created_at DESC"
)->fetchAll(PDO::FETCH_ASSOC);

// All Years
$allYears = $pdo->query("SELECT * FROM years ORDER BY year DESC")->fetchAll(PDO::FETCH_ASSOC);

// All Subjects with context
$allSubjects = $pdo->query(
    "SELECT sub.id, sub.name, sub.is_active, sem.name AS semester_name, l.name AS level_name
     FROM subjects sub
     JOIN semesters sem ON sub.semester_id = sem.id
     JOIN levels l ON sem.level_id = l.id
     ORDER BY l.name, sem.name, sub.name"
)->fetchAll(PDO::FETCH_ASSOC);

// Levels and Semesters for the add-subject form
$allLevels = $pdo->query("SELECT id, name FROM levels ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
$allSemesters = $pdo->query(
    "SELECT s.id, s.name, l.name AS level_name FROM semesters s JOIN levels l ON s.level_id = l.id ORDER BY l.name, s.name"
)->fetchAll(PDO::FETCH_ASSOC);

?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Administration - IAI DOCS</title>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=JetBrains+Mono:wght@400;700&family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DM Sans', sans-serif; background: #040c18; color: #c8ddf2; }
        
        /* Navbar matching index.html */
        .navbar { background: #07111f; padding: 15px 20px; border-bottom: 1px solid #1e3558; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 20px rgba(0,0,0,0.5); margin-bottom: 40px; }
        .navbar .logo { display:flex; align-items:center; text-decoration:none; color:#fff; font-family:'Bebas Neue',sans-serif; font-size:2rem; letter-spacing:0.05em; line-height:1; }
        .navbar .header-btn { font-family: 'JetBrains Mono', monospace; font-size:0.85rem; padding: 8px 16px; border: 1px solid #1e3558; border-radius: 6px; text-decoration: none; font-weight: 500; color: #c8ddf2; transition: all 0.3s; }
        .navbar .header-btn:hover { border-color: #00e5c4; color: #00e5c4; background: rgba(0,229,196,0.1); }
        
        .container { max-width: 1200px; margin: 0 auto; padding: 0 20px 40px; }

        /* Tabs */
        .tabs { display: flex; gap: 10px; margin-bottom: 24px; border-bottom: 1px solid #1e3558; padding-bottom: 10px; }
        .tab { font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; padding: 10px 20px; text-decoration: none; color: #4a6a8a; font-weight: 500; border-radius: 6px; transition: all 0.3s; }
        .tab:hover { color: #00e5c4; background: rgba(0,229,196,0.05); }
        .tab.active { color: #040c18; background: #00e5c4; font-weight: 700; box-shadow: 0 0 15px rgba(0,229,196,0.3); }

        /* Alerts */
        .alert { padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; font-weight: 500; font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; }
        .alert-success { background: rgba(16,185,129,0.1); color: #10b981; border: 1px solid rgba(16,185,129,0.2); }
        .alert-error { background: rgba(239,68,68,0.1); color: #ef4444; border: 1px solid rgba(239,68,68,0.2); }

        /* Table */
        table { width: 100%; border-collapse: collapse; background: #07111f; box-shadow: 0 4px 15px rgba(0,0,0,0.3); border-radius: 12px; overflow: hidden; border: 1px solid #1e3558; }
        th, td { padding: 14px 16px; border-bottom: 1px solid #1e3558; text-align: left; font-size: 0.9rem; }
        th { background: #0a1628; color: #a855f7; font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
        tr:last-child td { border-bottom: none; }
        tr:hover { background: #0a1628; }

        /* Buttons */
        .btn { font-family: 'JetBrains Mono', monospace; text-transform: uppercase; padding: 6px 14px; border: none; cursor: pointer; color: white; border-radius: 6px; font-weight: 500; font-size: 0.8rem; text-decoration: none; display: inline-block; transition: all 0.3s; }
        .btn-approve { background: rgba(16,185,129,0.1); color: #10b981; border: 1px solid #10b981; } .btn-approve:hover { background: #10b981; color: white; box-shadow: 0 0 10px rgba(16,185,129,0.4); }
        .btn-reject { background: rgba(239,68,68,0.1); color: #ef4444; border: 1px solid #ef4444; } .btn-reject:hover { background: #ef4444; color: white; box-shadow: 0 0 10px rgba(239,68,68,0.4); }
        .btn-view { background: transparent; color: #4a6a8a; border: 1px solid #4a6a8a; } .btn-view:hover { border-color: #c8ddf2; color: #c8ddf2; }
        .btn-primary { background: linear-gradient(135deg, #00e5c4, #3b82f6); color: white; border: none; font-weight: 700; } .btn-primary:hover { transform: translateY(-2px); box-shadow: 0 4px 15px rgba(0,229,196,0.4); }
        .btn-warning { background: rgba(245,158,11,0.1); color: #f59e0b; border: 1px solid #f59e0b; } .btn-warning:hover { background: #f59e0b; color: #040c18; box-shadow: 0 0 10px rgba(245,158,11,0.4); }
        .btn-docling { background: rgba(16,185,129,0.1); color: #10b981; border: 1px solid #10b981; } .btn-docling:hover { background: #10b981; color: white; box-shadow: 0 0 10px rgba(16,185,129,0.4); }
        .btn-sm { padding: 5px 10px; font-size: 0.75rem; }

        /* Forms */
        .form-card { background: #07111f; padding: 24px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.3); border: 1px solid #1e3558; margin-bottom: 24px; max-width: 500px; }
        .form-card h3 { margin-bottom: 16px; color: #fff; font-family: 'Bebas Neue', sans-serif; font-size: 1.5rem; letter-spacing: 0.05em; }
        .form-group { margin-bottom: 16px; }
        .form-group label { display: block; margin-bottom: 6px; font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #00e5c4; }
        .form-input { width: 100%; padding: 10px 14px; background: #040c18; border: 1px solid #1e3558; color: #c8ddf2; border-radius: 6px; font-family: 'DM Sans', sans-serif; font-size: 0.95rem; }
        .form-input:focus { outline: none; border-color: #3b82f6; box-shadow: 0 0 0 2px rgba(59,130,246,0.3); }

        .empty-state { background: #07111f; padding: 40px; text-align: center; border-radius: 12px; color: #4a6a8a; border: 1px solid #1e3558; font-family: 'JetBrains Mono', monospace; }
        .badge { display: inline-block; padding: 4px 10px; border-radius: 12px; font-size: 0.75rem; font-family: 'JetBrains Mono', monospace; font-weight: 600; text-transform: uppercase; }
        .badge-active { background: rgba(16,185,129,0.15); color: #10b981; }
        .badge-inactive { background: rgba(239,68,68,0.15); color: #ef4444; }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="../index.html" class="logo">⚙ IAI DOCS ADMIN</a>
        <a href="../index.html" class="header-btn">← Retour au site</a>
    </div>

    <div class="container">

        <?php if ($success): ?>
            <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
        <?php endif; ?>
        <?php if ($error): ?>
            <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <?php if (!empty($notifications)): ?>
            <?php foreach ($notifications as $notif): ?>
                <div class="alert <?= $notif['type'] === 'error' ? 'alert-error' : 'alert-success' ?>" style="display:flex; justify-content:space-between; align-items:center;">
                    <div>
                        <strong><?= htmlspecialchars($notif['title']) ?></strong><br>
                        <?= htmlspecialchars($notif['message']) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <!-- Tabs -->
        <div class="tabs">
            <a href="admin.php?tab=documents" class="tab <?= $tab === 'documents' ? 'active' : '' ?>">📄 Documents en Attente (<?= count($pendingDocs) ?>)</a>
            <a href="admin.php?tab=years" class="tab <?= $tab === 'years' ? 'active' : '' ?>">📅 Gérer Années</a>
            <a href="admin.php?tab=subjects" class="tab <?= $tab === 'subjects' ? 'active' : '' ?>">📚 Gérer Matières</a>
        </div>

        <!-- ==================== TAB: DOCUMENTS ==================== -->
        <?php if ($tab === 'documents'): ?>
            <?php if (empty($pendingDocs)): ?>
                <div class="empty-state">Aucun document en attente de validation.</div>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th>Titre</th>
                            <th>Matière</th>
                            <th>Type</th>
                            <th>Année</th>
                            <th>Niveau</th>
                            <th>Contributeur</th>
                            <th>Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pendingDocs as $doc): ?>
                        <tr>
                            <td><strong><?= htmlspecialchars($doc['title']) ?></strong></td>
                            <td><?= htmlspecialchars($doc['subject_name']) ?></td>
                            <td><?= htmlspecialchars($doc['type_name']) ?></td>
                            <td><?= htmlspecialchars($doc['year']) ?></td>
                            <td><?= htmlspecialchars($doc['level_name']) ?> — <?= htmlspecialchars($doc['semester_name']) ?></td>
                            <td><?= htmlspecialchars($doc['user_name'] ?? 'Anonyme') ?></td>
                            <td><?= htmlspecialchars($doc['created_at']) ?></td>
                            <td style="white-space: nowrap;">
                                <?php 
                                    $safeDraftTitle = preg_replace('/[^a-zA-Z0-9_\-]/', '_', $doc['title']);
                                    $hasDraft = file_exists(__DIR__ . '/../drafts/' . $safeDraftTitle . '.md') || !empty($doc['raw_markdown']); 
                                    
                                    $currentUserId = $_SESSION['user_id'] ?? 0;
                                    $isLocked = false;
                                    if (!empty($doc['locked_by']) && (int)$doc['locked_by'] !== $currentUserId) {
                                        $lockedTime = strtotime($doc['locked_at']);
                                        if ((time() - $lockedTime) < (15 * 60)) {
                                            $isLocked = true;
                                        }
                                    }
                                ?>
                                <?php if (!empty($doc['filename']) && $doc['filename'] !== 'markdown_direct.md'): ?>
                                    <a href="../uploads/<?= htmlspecialchars($doc['filename']) ?>" target="_blank" class="btn btn-view btn-sm">PDF Original</a>
                                <?php endif; ?>
                                
                                <?php if ($isLocked): ?>
                                    <span class="badge badge-inactive" style="margin-left:5px;">Verrouillé (En édition)</span>
                                <?php elseif ($hasDraft): ?>
                                    <a href="admin_edit.php?id=<?= $doc['id'] ?>" class="btn btn-warning btn-sm">Ouvrir le brouillon</a>
                                <?php else: ?>
                                    <form method="POST" action="admin_action.php" style="display:inline;" onsubmit="this.querySelector('button').innerText='Docling...';">
                                        <input type="hidden" name="id" value="<?= $doc['id'] ?>">
                                        <input type="hidden" name="action" value="generate_docling">
                                        <button type="submit" class="btn btn-docling btn-sm" title="Extraction locale">🚀 Docling</button>
                                    </form>
                                    <form method="POST" action="admin_action.php" style="display:inline;" onsubmit="this.querySelector('button').innerText='IA Vision...';">
                                        <input type="hidden" name="id" value="<?= $doc['id'] ?>">
                                        <input type="hidden" name="action" value="generate_ai">
                                        <button type="submit" class="btn btn-primary btn-sm" title="Vision AI">🧠 IA Vision</button>
                                    </form>
                                <?php endif; ?>
                                
                                <form method="POST" action="admin_action.php" style="display:inline;">
                                    <input type="hidden" name="id" value="<?= $doc['id'] ?>">
                                    <input type="hidden" name="action" value="reject">
                                    <button type="submit" class="btn btn-reject btn-sm" onclick="return confirm('Rejeter ce document ?');">Rejeter</button>
                                </form>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>

        <!-- ==================== TAB: YEARS ==================== -->
        <?php elseif ($tab === 'years'): ?>
            <div class="form-card">
                <h3>➕ Ajouter une Année</h3>
                <form method="POST" action="admin.php?tab=years">
                    <input type="hidden" name="form_action" value="add_year">
                    <div class="form-group">
                        <label>Année académique</label>
                        <input type="number" name="year" class="form-input" min="2000" max="2099" value="<?= date('Y') ?>" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                </form>
            </div>

            <table>
                <thead><tr><th>ID</th><th>Année</th><th>Ajoutée le</th></tr></thead>
                <tbody>
                    <?php foreach ($allYears as $y): ?>
                    <tr>
                        <td><?= $y['id'] ?></td>
                        <td><strong><?= $y['year'] ?></strong></td>
                        <td><?= $y['created_at'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        <!-- ==================== TAB: SUBJECTS ==================== -->
        <?php elseif ($tab === 'subjects'): ?>
            <div class="form-card">
                <h3>➕ Ajouter une Matière</h3>
                <form method="POST" action="admin.php?tab=subjects">
                    <input type="hidden" name="form_action" value="add_subject">
                    <div class="form-group">
                        <label>Nom de la matière</label>
                        <input type="text" name="subject_name" class="form-input" placeholder="Ex: Algorithmique" required>
                    </div>
                    <div class="form-group">
                        <label>Semestre</label>
                        <select name="semester_id" class="form-input" required>
                            <option value="">Sélectionner</option>
                            <?php foreach ($allSemesters as $sem): ?>
                                <option value="<?= $sem['id'] ?>"><?= htmlspecialchars($sem['level_name']) ?> — <?= htmlspecialchars($sem['name']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Ajouter</button>
                </form>
            </div>

            <table>
                <thead><tr><th>Matière</th><th>Niveau</th><th>Semestre</th><th>Statut</th><th>Action</th></tr></thead>
                <tbody>
                    <?php foreach ($allSubjects as $sub): ?>
                    <tr>
                        <td><strong><?= htmlspecialchars($sub['name']) ?></strong></td>
                        <td><?= htmlspecialchars($sub['level_name']) ?></td>
                        <td><?= htmlspecialchars($sub['semester_name']) ?></td>
                        <td>
                            <?php if ($sub['is_active']): ?>
                                <span class="badge badge-active">Active</span>
                            <?php else: ?>
                                <span class="badge badge-inactive">Inactive</span>
                            <?php endif; ?>
                        </td>
                        <td>
                            <form method="POST" action="admin.php?tab=subjects" style="display:inline;">
                                <input type="hidden" name="form_action" value="toggle_subject">
                                <input type="hidden" name="subject_id" value="<?= $sub['id'] ?>">
                                <button type="submit" class="btn <?= $sub['is_active'] ? 'btn-warning' : 'btn-approve' ?> btn-sm">
                                    <?= $sub['is_active'] ? 'Désactiver' : 'Activer' ?>
                                </button>
                            </form>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
</body>
</html>
